title: Welcome to my site.
author: fanke
email: mayizhaixing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ML method example

# social links
twitter_username: LittleAnt168
github_username:  LittleAnt168

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
